platform :ios, '12.0'

target 'HM_SwiftDemo' do


use_frameworks!


# 屏蔽所有第三方框架警告
inhibit_all_warnings!

pod 'com_huntmobi_web2app', '~> 3.0.1'


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

end




